{
 "title": "AmneziaWG",
 "description": "Metrics for AmneziaWG VPN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Clients Summary Traffic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(awg_received_bytes[$__interval])",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Latest Handshakes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(awg_latest_handshake_seconds[$__interval]) < 1000000",
     "legendFormat": "{{client_name}}"
    }
   ]
  },
  {
   "title": "Received/Send Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(awg_sent_bytes[$__rate_interval]) != 0",
     "legendFormat": "Sent {{client_name}}"
    },
    {
     "expr": "-rate(awg_received_bytes[$__rate_interval]) != 0",
     "legendFormat": "Received {{client_name}}"
    }
   ]
  }
 ]
}